### PR TITLE
Update order of links on NavBar

### LINKED ISSUE #1149: Re-order links on Nav Bar, adjust titles
Currently, the order of the links on the gnomAD browsers navigation bar is: 
- About, Team,  News, Changelog, Downloads, Policies, Publications, Contact, Help

Screenshot 2023-08-04 at 14 06 40

Based on their relative popularity, the order should be changed to: 
- About, Team, Policies, Publications, News (to be changed to Blog), Changelog, Downloads, Help/FAQ.

In addition, the link for "News" should be changed to say "Blog"

This will require a change on the gnomAD Blog as well as on the gnomAD Browser, to keep the two in sync.

### PR DESCRIPTION
**Pull request by iamsadat**
Fixes #1149

### CODE REVIEW

**Comment by mattsolo1** [comment]
@rileyhgrant can you please advise @iamsadat on how to get checks to pass?

**Review by rileyhgrant — CHANGES_REQUESTED** [review]
Hey @iamsadat 

Thanks for looking at this! Here are a few comments we'd like you to address:

1. The convention for naming both Pull Requests and Commits in this Repo is to use present tense, sentence case, and to be descriptive. i.e. the title should be "Update order of links on NavBar" and similarly the commit message should be changed to something like "Update order of links on the NavBar"
2. We use Jest for testing on the frontend. For many of these simpler components the tests are simple snapshot tests. On your local machine, this should be as simple as running `yarn jest --no-cache` from the root directory, followed by a `yarn jest --no-cache -u <YOUR-TEST-FILE>`, in this case something like: `yarn jest --no-cache -u NavBar`. The `-u` flag specifies that Jest should update the snapshot generated by the test.
3. As mentioned in the issue, this will have to be merged in sync with a PR on the gnomAD Blog, since there are two seperate applications. Since I'll be merging this, I can make the other PR.

Thanks again for taking a look at this, this also helps us get our docs in better order (we can do a better job of specifying our conventions, as well as documenting what tests to run locally). Let me know if anything is unclear.

Riley

**Comment by iamsadat** [comment]
Hey Riley, Thanks for the help and sorry about the mess I've created. But I've used the naming convention as per the repo. The snapshot has been updated too.
Please let me know if any other changes are required.

**Comment by phildarnowsky-broad** [comment]
@iamsadat Just wanted to swing by and say thanks for contributing!

**Comment by iamsadat** [comment]
@phildarnowsky-broad 
Looking forward to diving even deeper into the project and making a meaningful contributions!

**Review by rileyhgrant — APPROVED** [review]
LGTM, thanks @iamsadat!

I'll merge this PR and squash all the commits into a single one.

Thanks again :)

**Pull request merged**
