### PR TITLE
Centralized metadata part 5

### PR DESCRIPTION
**Pull request by phildarnowsky-broad**
Last in this series. You will definitely want to take this one commit at a time; luckily, you'll see the same techniques over and over again, so that should help.

### CODE REVIEW

**Review by rileyhgrant — APPROVED** [review]
Nice work with all the tests, they look good to my eyes.

For this review I looked over the changes (commit by commit as you suggested, thanks for the heads up), and started a local browser and checked the relevant pages (Mitochondrial Variant, Mitochondrial Region, Transcript of multiple flavors, Region of multiple flavors, Gene of multiple flavors) and everything appeared stable. Nicely done with this centralized metadata project.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 figured out how to quiet those "Invalid arguments" warnings. The test suite does still give some other warnings due to GBTK components that need to get updated.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 anything further here?

**Comment by mattsolo1** [comment]
Nope, LGTM!

**Pull request merged**
