### PR TITLE
Convert existing tests and buildHelp.js script to TypeScript

### PR DESCRIPTION
**Pull request by phildarnowsky-broad**
Here, we convert our backlog of existing tests in JS to TypeScript. We also convert `buildHelp.js` in the same commit, which is a thing that I would normally call out myself on the theory that converting that script would merit its own separate commit. However, there is a dependency in there that's probably not readily obvious, at least, it sure took me a while to figure out why changing the tests over to TS broke the apparently unrelated script. I can go into more detail if you want about that, but it's not all that interesting.

### CODE REVIEW

**Comment by phildarnowsky-broad** [comment]
TL;DR: the code in `buildHelp.js` that generated the list of JS/TS (as opposed to Markdown) files to use was erroneously including tests, i.e. `spec.tsx` files, which of course never came up before since there weren't any tests. I'm not 100% clear on the details, but it seems that whereas JS accepted this uncritically, TS has higher standards. Fixing that was as simple as throwing in a `filter` that matched all files except for tests. Everything else I did in that file was just a bit of refactoring, and adjusting a few things that the TS linter didn't like.

**Review by rileyhgrant — APPROVED** [review]
Looks good to me!

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant if you haven't yet, could you please pull this branch and manually verify that the build script is giving good results? Given that this (apparently obvious) script has been trouble a couple of times in a brief period already, I'd feel better if you double-checked this one for me on your own machine.

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant specifically, I'd appreciate if you could test both `yarn build` and `yarn start` and verify by eye that the help pages, especially the haplotype ones that you modified recently, haven't regressed

**Comment by rileyhgrant** [comment]
> @rileyhgrant if you haven't yet, could you please pull this branch and manually verify that the build script is giving good results? Given that this (apparently obvious) script has been trouble a couple of times in a brief period already, I'd feel better if you double-checked this one for me on your own machine.

@phildarnowsky-broad Oops yeah, I should have clarified when I approved that things are working on my machine. Good points on wanting to be especially sure seeing as its this script. 

Both running `yarn start`, as well as `yarn build` then checking the `npx live-server` from the `gnomad-browser/browser/dist/public` folder result in a functional help page on my machine. The `.tsx` files that get used as part of the build, and were causing issues for a tiny bit, are working, as are the `.md` files. The exception of the one noted in issue #969, which is not directly related to the `buildHelp.ts` file, and has a standalone issue filed.

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant great, thanks--I figured you probably had checked these on your own initiative, but I was just looking over this PR and saw that, while I had meant to ask you explicitly to do so at the time I opened the PR, apparently I forgot to do so. anyway, good to hear that we're in business, I'll merge.

**Pull request merged**
